plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.165'
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://maven.saps.dev/releases' }
    maven { url = 'https://cursemaven.com' }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
}

minecraft {
    mappings channel: 'official', version: minecraft_version
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly 'dev.ftb.mods:ftb-chunks-neoforge:2101.1.14'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
